# Generated by Django 5.2.9 on 2025-12-17 13:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0002_venuemodel_category_venuemodel_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredTopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(help_text='Position in sponsored top (1 = first)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('note', models.CharField(blank=True, help_text="Admin note (e.g., 'Paid promotion until Dec 31')", max_length=100)),
                ('venue', models.ForeignKey(limit_choices_to={'is_active': True, 'is_moderated': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_positions', to='venues.venuemodel')),
            ],
            options={
                'db_table': 'sponsored_top',
                'ordering': ['position'],
                'unique_together': {('venue', 'position')},
            },
        ),
    ]
