# Generated by Django 5.2.9 on 2025-12-10 20:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venueowners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=35)),
                ('schedule', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to=core.services.file_service.upload_venue_photo)),
                ('house', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('street', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')])),
                ('city', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')])),
                ('region', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')])),
                ('country', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')])),
                ('average_check', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rating', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_moderated', models.BooleanField(default=False)),
                ('bad_word_attempts', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('daily_views', models.IntegerField(default=0)),
                ('weekly_views', models.IntegerField(default=0)),
                ('monthly_views', models.IntegerField(default=0)),
                ('last_view_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='venueowners.venueownermodel')),
            ],
            options={
                'db_table': 'venues',
            },
        ),
    ]
