# Generated by Django 5.2.9 on 2025-12-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='category',
            field=models.CharField(choices=[('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('mixed', 'Mixed')], default='mixed', max_length=10),
        ),
        migrations.AddField(
            model_name='venuemodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='venuemodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
