# Generated by Django 5.2.9 on 2025-12-20 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venuemodel_category_venuemodel_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuemodel',
            name='city',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-Z][a-zА-я]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='country',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator('^[A-Z][a-zА-я]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='region',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator('^[A-Z][a-zА-я]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='street',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-Z][a-zА-я]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')]),
        ),
    ]
