# Generated by Django 5.2.9 on 2025-12-21 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_alter_venuemodel_city_alter_venuemodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuemodel',
            name='city',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЁЇІЄҐ][a-zа-яёїієґA-ZА-ЯЁЇІЄҐ -]*$', 'Тільки літери (латинські або кирилиця), пробіли, дефіси. Починається з великої літери. Менше 35 символів.')]),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='country',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЁЇІЄҐ][a-zа-яёїієґA-ZА-ЯЁЇІЄҐ -]*$', 'Тільки літери (латинські або кирилиця), пробіли, дефіси. Починається з великої літери. Менше 35 символів.')]),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='region',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЁЇІЄҐ][a-zа-яёїієґA-ZА-ЯЁЇІЄҐ -]*$', 'Тільки літери (латинські або кирилиця), пробіли, дефіси. Починається з великої літери. Менше 35 символів.')]),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='street',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЁЇІЄҐ][a-zа-яёїієґA-ZА-ЯЁЇІЄҐ -]*$', 'Тільки літери (латинські або кирилиця), пробіли, дефіси. Починається з великої літери. Менше 35 символів.')]),
        ),
    ]
