# Generated by Django 5.2.9 on 2025-12-17 13:40

import django.db.models.deletion
from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0002_venuemodel_category_venuemodel_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to=core.services.file_service.upload_news_photo)),
                ('type', models.CharField(choices=[('general', 'General'), ('promotion', 'Promotion'), ('event', 'Event')], default='general', max_length=20)),
                ('is_paid', models.BooleanField(default=False, help_text='Paid promotions appear in special sections')),
                ('venue', models.ForeignKey(blank=True, help_text='If null — global news, else — venue-specific', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='venues.venuemodel')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-created_at'],
            },
        ),
    ]
