# Generated by Django 5.2.9 on 2025-12-17 20:37

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.services.file_service.upload_news_photo),
        ),
    ]
