# Generated by Django 5.2.9 on 2025-12-17 13:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0002_venuemodel_category_venuemodel_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PiyachokRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender_preference', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], default='A', max_length=1)),
                ('budget', models.PositiveIntegerField(help_text='Budget in UAH', validators=[django.core.validators.MinValueValidator(1)])),
                ('who_pays', models.CharField(choices=[('me', 'I pay'), ('them', 'They pay'), ('split', 'Split')], default='split', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True, help_text='Additional message')),
                ('preferred_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piyachok_requests', to='venues.venuemodel')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piyachok_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'piyachok_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('chat_room_id', models.CharField(blank=True, help_text='Unique room name for match chat', max_length=100, unique=True)),
                ('suggested_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_matches', to='venues.venuemodel')),
                ('request1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_request1', to='piyachok.piyachokrequestmodel')),
                ('request2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_request2', to='piyachok.piyachokrequestmodel')),
            ],
            options={
                'db_table': 'piyachok_matches',
                'ordering': ['-created_at'],
                'unique_together': {('request1', 'request2')},
            },
        ),
    ]
