# Generated by Django 5.2.9 on 2025-12-17 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piyachok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmodel',
            name='request2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_request2', to='piyachok.piyachokrequestmodel'),
        ),
    ]
