# Generated by Django 5.2.9 on 2025-12-10 20:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_critic', models.BooleanField(default=False)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,14}$', 'Only alpha characters are allowed! Less than 15 characters are allowed.')])),
                ('surname', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,19}$', 'Only alpha characters are allowed! Less than 20 characters are allowed.')])),
                ('gender', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,7}$', 'Only alpha characters are allowed! Less than 8 characters are allowed.')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('house', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('street', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')])),
                ('city', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')])),
                ('region', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')])),
                ('country', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-z][a-z]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
