# Generated by Django 5.2.9 on 2025-12-20 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-Z][a-zА-я]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='country',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-Z][a-zА-я]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[A-Z][a-zА-я]{,7}$', 'Only alpha characters are allowed! Less than 8 characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Z][a-zА-я]{,14}$', 'Only alpha characters are allowed! Less than 15 characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='region',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-Z][a-zА-я]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='street',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-Z][a-zА-я]{,34}$', 'Only alpha characters are allowed! Less than 35 characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z][a-zА-я]{,19}$', 'Only alpha characters are allowed! Less than 20 characters are allowed.')]),
        ),
    ]
