# Generated by Django 5.2.9 on 2025-12-21 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profilemodel_city_alter_profilemodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЁЇІЄҐ][a-zа-яёїієґA-ZА-ЯЁЇІЄҐ -]*$', 'Тільки літери (латинські або кирилиця), пробіли, дефіси. Починається з великої літери. Менше 35 символів.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='country',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЁЇІЄҐ][a-zа-яёїієґA-ZА-ЯЁЇІЄҐ -]*$', 'Тільки літери (латинські або кирилиця), пробіли, дефіси. Починається з великої літери. Менше 35 символів.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЁЇІЄҐ][a-zа-яёїієґA-ZА-ЯЁЇІЄҐ -]*$', 'Тільки літери (латинські або кирилиця), пробіли, дефіси. Починається з великої літери.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЁЇІЄҐ][a-zа-яёїієґA-ZА-ЯЁЇІЄҐ -]*$', 'Тільки літери (латинські або кирилиця), пробіли, дефіси. Починається з великої літери.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='region',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЁЇІЄҐ][a-zа-яёїієґA-ZА-ЯЁЇІЄҐ -]*$', 'Тільки літери (латинські або кирилиця), пробіли, дефіси. Починається з великої літери. Менше 35 символів.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='street',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЁЇІЄҐ][a-zа-яёїієґA-ZА-ЯЁЇІЄҐ -]*$', 'Тільки літери (латинські або кирилиця), пробіли, дефіси. Починається з великої літери. Менше 35 символів.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-ZА-ЯЁЇІЄҐ][a-zа-яёїієґA-ZА-ЯЁЇІЄҐ -]*$', 'Тільки літери (латинські або кирилиця), пробіли, дефіси. Починається з великої літери.')]),
        ),
    ]
