# Generated by Django 5.2.9 on 2025-12-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profilemodel_city_alter_profilemodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(max_length=8),
        ),
    ]
